FROM node:14-alpine

RUN mkdir /app-client
WORKDIR /app-client

COPY package.json /app-client
RUN npm install

COPY ./src /app-client/src
COPY ./public /app-client/public

EXPOSE 3000
EXPOSE 35729

CMD ["npm", "run", "client"]