FROM node:14-alpine

RUN mkdir /app-server
WORKDIR /app-server

COPY package.json /app-server
RUN npm install

COPY ./server /app-server/server
COPY ./public /app-server/public

CMD ["npm", "run", "server"]